version: '3'

services:
  app:
    build: .
    ports:
      - "9000:8000"
    volumes:
      - .:/app
    environment:
      - PORT=8000
      - PYTHONPATH=/app
      # Add your other environment variables here
      # - DATABASE_URL=...
      # - PAYPAY_API_KEY=...
    restart: unless-stopped
