[project]
name = "rocket-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "opencv-python-headless>=4.8.0",
    "ultralytics>=8.0.0",
    "numpy==1.23.5",
]
